import { List, removeMiddle, sumList, sumReverse, intersect, intersector } from './list';

let list = new List();
list.add('a');
list.add('a');
list.add('a');
list.add('a');
list.add('a');
list.add('a');
console.log(list.toString());
list.uniq();
console.log(list.toString());
list.add('a');
list.add('a');
list.add('a');
list.add('a');
list.add('a');
list.add('a');
console.log(list.toString());
list.uniqInPlace();
console.log(list.toString());
list.add('b');
list.add('x');
list.add('g');
list.add('n');
list.add('x');
list.add('f');
console.log(list.toString());
console.log('4th from last:', list.fromLast(4).data);
console.log('2nd from last:', list.fromLast(2).data);
try {
  console.log(list.fromLast(10).data);
} catch (err) {
  console.error(err.message);
}
console.log(list.toString());
removeMiddle(list.fromLast(4));
console.log(list.toString());
list.partition('n');
console.log(list.toString());
list.partition('x');
console.log(list.toString());
let num_a = new List();
num_a.add(6);
num_a.add(1);
num_a.add(7);
let num_b = new List();
num_b.add(2);
num_b.add(9);
num_b.add(5);
console.log(sumReverse(num_a, num_b).toString());
num_a = new List();
num_a.add(7);
num_a.add(1);
num_a.add(6);
num_b = new List();
num_b.add(5);
num_b.add(9);
num_b.add(2);
console.log(sumList(num_a, num_b).toString());
list = new List();
list.add('a');
list.add('c');
list.add('b');
list.add('a');
console.log(list.toString());
console.log(list.isPalindrome());
let a = new List();
let b = new List();
a.add('a');
a.add('b');
a.add('c');
b.head.next = a.head.next;
b.add('x');
b.add('x');
b.add('x');
b.add('x');
console.log(a.toString(), b.toString());
console.log(intersect(a, b));
console.log(intersect(a, list));
console.log(intersector(a, b));
console.log(b.loopHead());
b.head.next.next.next = b.head.next;
console.log(b.loopHead());

